<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Exams</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Natalie's Site</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="Assignments.html">Assignments</a>
</li>
<li>
  <a href="Exams.html">Exams</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Exams</h1>

</div>


<div id="exam-1" class="section level1">
<h1>Exam 1</h1>
<ol style="list-style-type: lower-alpha">
<li><p>Create a folder in your computer (a good place would be under Crim 250, Exams).</p></li>
<li><p>Download the dataset from the Canvas website (fatal-police-shootings-data.csv) onto that folder, and save your Exam 1.Rmd file in the same folder.</p></li>
<li><p>Download the README.md file. This is the codebook.</p></li>
<li><p>Load the data into an R data frame.</p></li>
</ol>
<pre class="r"><code># setwd(&quot;~/Desktop/Fall 2021/CRIM 250/Crim 250 - Exam 1&quot;)
shootings &lt;- read.csv(&quot;fatal-police-shootings-data.csv&quot;)
shootings.untouched &lt;- shootings
View(shootings)</code></pre>
<div id="problem-1-10-points" class="section level2">
<h2>Problem 1 (10 points)</h2>
<ol style="list-style-type: lower-alpha">
<li>Describe the dataset. This is the source: <a href="https://github.com/washingtonpost/data-police-shootings" class="uri">https://github.com/washingtonpost/data-police-shootings</a> . Write two sentences (max.) about this.</li>
</ol>
<p>The Washington Post compiled this dataset from a variety of sources (ie. local news, social media, etc.), and it contains relevant information looking at fatal police shootings in the United States dating back to January 1, 2015. The data includes demographics about the victims, as well as information on where the shootings occurred and other details that might be interesting to examine in relation to the shooting.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>How many observations are there in the data frame?</li>
</ol>
<pre class="r"><code>dim(shootings)</code></pre>
<pre><code>## [1] 6594   17</code></pre>
<p>There are 6,594 rows (number of fatal shootings) and 17 different columns, each containing information respective to the row.</p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Look at the names of the variables in the data frame. Describe what “body_camera”, “flee”, and “armed” represent, according to the codebook. Again, only write one sentence (max) per variable.</li>
</ol>
<pre class="r"><code>names(shootings)</code></pre>
<pre><code>##  [1] &quot;id&quot;                      &quot;name&quot;                   
##  [3] &quot;date&quot;                    &quot;manner_of_death&quot;        
##  [5] &quot;armed&quot;                   &quot;age&quot;                    
##  [7] &quot;gender&quot;                  &quot;race&quot;                   
##  [9] &quot;city&quot;                    &quot;state&quot;                  
## [11] &quot;signs_of_mental_illness&quot; &quot;threat_level&quot;           
## [13] &quot;flee&quot;                    &quot;body_camera&quot;            
## [15] &quot;longitude&quot;               &quot;latitude&quot;               
## [17] &quot;is_geocoding_exact&quot;</code></pre>
<p>According to the codebook, “body_camera” refers to whether or not the officer involved in the shooting was wearing a body camera that could have recorded parts of the shooting. The “flee” variable contains data on whether the victim was moving away from the officer during the incident. The “armed” column gives us information on whether the victim was armed, which might have influenced the officer’s decision to take action.</p>
<ol start="4" style="list-style-type: lower-alpha">
<li>What are three weapons that you are surprised to find in the “armed” variable? Make a table of the values in “armed” to see the options.</li>
</ol>
<pre class="r"><code>surprising_weapons &lt;- table(unique(shootings$armed))
View(surprising_weapons)</code></pre>
<p>Three surprising weapons I found were interesting include the binoculars, microphone, and wasp spray.</p>
</div>
<div id="problem-2-10-points" class="section level2">
<h2>Problem 2 (10 points)</h2>
<ol style="list-style-type: lower-alpha">
<li>Describe the age distribution of the sample. Is this what you would expect to see?</li>
</ol>
<pre class="r"><code>hist(shootings$age,
     main = &quot;Histogram of Ages&quot;,
     xlab = &quot;Age&quot;,
     ylab = &quot;Frequency&quot;,
     xlim = c(0,100))</code></pre>
<p><img src="Exams_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>This histogram, which shows the distributions of the victim’s ages, shows that the victims are mostly in their 30’s. This is overall not surprising, as the median age of adults in the US are roughly 38 years old, so it would make sense that this age range has the most number of victims, also by chance.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>To understand the center of the age distribution, would you use a mean or a median, and why? Find the one you picked.</li>
</ol>
<pre class="r"><code>shootings$age[which(is.na(shootings$age))] &lt;- 0
length(shootings$age[shootings$age == 0])</code></pre>
<pre><code>## [1] 308</code></pre>
<pre class="r"><code>mean(shootings$age)</code></pre>
<pre><code>## [1] 35.38854</code></pre>
<pre class="r"><code>median(shootings$age)</code></pre>
<pre><code>## [1] 34</code></pre>
<p>This graph is right skewed which means that the mean is greater than the median which is greater than the mode. Because of this, I would probably look at the median, as this value will be the middle value and most accurate number. We can remove the missing values marked as “NA” in the dataset which will allow us to perform calculations on the data that is reported; there are only 308 missing values, and in a dataset with 6,594 observations, this should not disrupt the data too much. The median of the ages reported in the shootings comes out to be 34 years old, which makes sense when comparing this value to the histogram showing the distributions of the ages above.</p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Describe the gender distribution of the sample. Do you find this surprising?</li>
</ol>
<pre class="r"><code>summary(shootings$gender)</code></pre>
<pre><code>##         F    M 
##    3  293 6298</code></pre>
<p>There are disproportionately more males (6298 cases reported) reported to be fatal victims of police shootings than there are females (293 cases reported). This is not surprising to me, especially because I feel like I more often have heard of males getting shot by police. This has been reflected by the news, especially with all the Black men getting fatally shot by police officers.</p>
</div>
<div id="problem-3-10-points" class="section level2">
<h2>Problem 3 (10 points)</h2>
<ol style="list-style-type: lower-alpha">
<li>How many police officers had a body camera, according to news reports? What proportion is this of all the incidents in the data? Are you surprised that it is so high or low?</li>
</ol>
<pre class="r"><code>length(which(shootings$body_camera == &quot;True&quot;))</code></pre>
<pre><code>## [1] 910</code></pre>
<pre class="r"><code>length(which(shootings$body_camera == &quot;False&quot;))</code></pre>
<pre><code>## [1] 5684</code></pre>
<pre class="r"><code>910+5684</code></pre>
<pre><code>## [1] 6594</code></pre>
<pre class="r"><code>(910/6594)*100</code></pre>
<pre><code>## [1] 13.80042</code></pre>
<p>There were 910 police officers who reported wearing body cameras, compared to 5,684 officers who reported that they were not wearing cameras. This only equates to 13.8% roughly, which is a low proportion. This is also not surprised that this is so low, and some hypotheses challenge that body cameras are effective in decreasing police brutality; although, the studies looking at this are relatively inconclusive. The fact that there were some instances in this data, where the officer was wearing a body camera, and the victim was still fatally shot, shows that body cameras are not fully effective and killings will happen even when officers are wearing them.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>In how many of the incidents was the victim fleeing? What proportion is this of the total number of incidents in the data? Is this what you would expect?</li>
</ol>
<pre class="r"><code>summary(shootings$flee)</code></pre>
<pre><code>##                     Car        Foot Not fleeing       Other 
##         491        1058         845        3952         248</code></pre>
<pre class="r"><code>1058+845</code></pre>
<pre><code>## [1] 1903</code></pre>
<pre class="r"><code>1903/6594</code></pre>
<pre><code>## [1] 0.2885957</code></pre>
<p>A total of 1,903 victims were reported to be fleeing, whether this is by car or by foot. This is roughly 28.9% of the victims in the dataset who were reported to be fleeing. This seems about accurate, or even slightly low, although my knowledge on specifics during police interactions is pretty limited.</p>
</div>
<div id="problem-4-10-points---answer-only-one-of-these-a-or-b." class="section level2">
<h2>Problem 4 (10 points) - Answer only one of these (a or b).</h2>
<ol style="list-style-type: lower-alpha">
<li>Describe the relationship between the variables “body camera” and “flee” using a stacked barplot. What can you conclude from this relationship?</li>
</ol>
<p><em>Hint 1: The categories along the x-axis are the options for “flee”, each bar contains information about whether the police officer had a body camera (vertically), and the height along the y-axis shows the frequency of that category).</em></p>
<p><em>Hint 2: Also, if you are unsure about the syntax for barplot, run ?barplot in R and see some examples at the bottom of the documentation. This is usually a good way to look up the syntax of R code. You can also Google it.</em></p>
<pre class="r"><code>tab.camflee &lt;- table(shootings$body_camera, shootings$flee)
barplot(tab.camflee,
        main = &quot;Barchart - Relationship Between Cameras and Fleeing&quot;,
        xlab = &quot;Fleeing&quot;,
        ylab = &quot;Frequency&quot;,
        legend.text = rownames(tab.camflee),
        beside = FALSE,
        ylim = c(0,4000))</code></pre>
<p><img src="Exams_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>This barchart shows the relationship between wearing a body camera and when the victims were fleeing. In terms of frequency, there were more officers wearing a body camera in the instances where the victim was not fleeing, but in terms of proportions, there were probably equal or even lesser number of officers wearing cameras when the victim was fleeing. Other than that, it is clear that in this dataset, officers were way more likely to not be wearing cameras across the board, no matter if the victim was fleeing or not.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Describe the relationship between age and race by using a boxplot. What can you conclude from this relationship?</li>
</ol>
<p><em>Hint 1: The categories along the x-axis are the race categories and the height along the y-axis is age.</em></p>
<p><em>Hint 2: Also, if you are unsure about the syntax for boxplot, run ?boxplot in R and see some examples at the bottom of the documentation. This is usually a good way to look up the syntax of R code. You can also Google it.</em></p>
<p><strong>Your answer here.</strong></p>
</div>
<div id="extra-credit-10-points" class="section level2">
<h2>Extra credit (10 points)</h2>
<ol style="list-style-type: lower-alpha">
<li>What does this code tell us?</li>
</ol>
<pre class="r"><code>mydates &lt;- as.Date(shootings$date)
head(mydates)
(mydates[length(mydates)] - mydates[1])</code></pre>
<p>The first line of code is changing the values in the date column and converting them to the character representation of how dates are in a calendar. This will allow us to manipulate the data in terms of date specific analysis, rather than having to treat it as the value that it is in the input stage. head(mydates) allows us to look at the first few values of the newly changed data. The last line of code allows us to look at the difference from where we are now, to the origin of the data, or the first date that was input.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>On Friday, a new report was published that was described as follows by The Guardian: “More than half of US police killings are mislabelled or not reported, study finds.” Without reading this article now (due to limited time), why do you think police killings might be mislabelled or underreported?</li>
</ol>
<p>I think there are many reasons why police killings would be mislabelled or underreported. There are many reasons why someone in the reporting process would want to change or withhold information in order to protect the officers involved in the shooting and the police force as a whole. I think it is important to take these factors into consideration when looking at any data that goes through the policing system, as there is a lot of personal incentive to not provide the whole truth, especially when police are under the microscope right now and some may feel the need to alter or not provide certain details in order to protect themselves.</p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Regarding missing values in problem 4, do you see any? If so, do you think that’s all that’s missing from the data?</li>
</ol>
<pre class="r"><code>summary(shootings$flee)</code></pre>
<pre><code>##                     Car        Foot Not fleeing       Other 
##         491        1058         845        3952         248</code></pre>
<pre class="r"><code>summary(shootings$body_camera)</code></pre>
<pre><code>## False  True 
##  5684   910</code></pre>
<p>There are missing values in the data we used for problem 4, specifically for the variable looking at victim fleeing. That is most likely not all the data that is missing from this dataset, as it is hard to compile complete information when looking at data like this. Overall, this dataset is pretty complete, and while it is always best practice to try to get as much information as possible, with such a large number of observations, missing data is not always the biggest deal. A lot of the times, you have to work with what you are provided with.</p>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
